_target_: hulc.models.encoders.goal_encoders.LanguageGoalEncoder_Mdetr
in_features: 768
hidden_size: 2048
latent_goal_features: 32
l2_normalize_goal_embeddings: False
activation_function: ReLU #ELU
word_dropout_p: 0.0
